version: '3.7'

services:

  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    container_name: '${PROJECT_NAME}_mariadb'
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
#      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - './mariadb-data:/var/lib/mysql'
      - './mariadb-init:/docker-entrypoint-initdb.d'

  phpmyadmin:
    image: phpmyadmin
    container_name: '${PROJECT_NAME}_pma'
    ports:
      - 0:80
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=$DB_USER
      - PMA_PASSWORD=$DB_PASSWORD
    depends_on:
      - mariadb
    labels:
      - 'traefik.http.routers.${PROJECT_NAME}_pma.rule=Host(`pma.${PROJECT_BASE_URL}`)'
  php:
    user: root
    command: "php-fpm -R"
    environment:
      PHP_FPM_USER: root
      PHP_FPM_GROUP: root
    image: 'wodby/drupal-php:$PHP_TAG'
    container_name: '${PROJECT_NAME}_php'
    environment:
      PHP_SENDMAIL_PATH: '/usr/sbin/sendmail -t -i -S mailhog:1025'
    volumes:
      - '.:$PROJECT_DIR'
  crond:
    image: 'wodby/drupal-php:$PHP_TAG'
    container_name: '${PROJECT_NAME}_crond'
    environment:
      CRONTAB: 0 * * * * drush -r ${PROJECT_DIR}/htdocs cron
    command: sudo -E LD_PRELOAD=/usr/lib/preloadable_libiconv.so crond -f -d 0
    volumes:
      - '.:${PROJECT_DIR}'
  nginx:
    image: 'wodby/nginx:$NGINX_TAG'
    container_name: '${PROJECT_NAME}_nginx'
    ports:
      - 0:80
    depends_on:
      - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: 'off'
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: ${PROJECT_DIR}/htdocs
      NGINX_VHOST_PRESET: $NGINX_VHOST_PRESET
    volumes:
      - '.:${PROJECT_DIR}'
    labels:
      - 'traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`${PROJECT_BASE_URL}`)'

  mailhog:
    image: mailhog/mailhog
    container_name: '${PROJECT_NAME}_mailhog'
    environment:
      MH_HOSTNAME: mailhog.${PROJECT_BASE_URL}
    ports:
      - 0:8025
    labels:
      - 'traefik.http.services.${PROJECT_NAME}_mailhog.loadbalancer.server.port=8025'
      - 'traefik.http.routers.${PROJECT_NAME}_mailhog.rule=Host(`mailhog.${PROJECT_BASE_URL}`)'
